#!/usr/bin/env python3
"""Generate assets/css/industry-home.css from homepage.css.

The industry template reuses the homepage's components (service plates,
terms accordion, pricing tiers, founder, admit-one ticket, buttons) rather
than restyling them. Instead of copying rules, this re-scopes homepage.css
from the homepage body class onto `.apex-industry-page .apx`, the wrapper the
industry template puts around those components. Re-run after any
homepage.css change:  python3 scripts/build-industry-css.py

A reset block is prepended at the same specificity: the industry page also
loads main.css (for its hero), which styles some of the same class names
(.btn, .h2, .container, .book, .founder, .founder__stats). `all: revert` drops those
landing-page rules back to the browser default so only the homepage's
declarations, which come after it, apply.
"""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSS = ROOT / 'wordpress/apex-landing-page/assets/css'
SCOPE = '.apex-industry-page .apx'

src = (CSS / 'homepage.css').read_text()
out = src.replace('body.apex-home-page', SCOPE).replace('.apex-home-page', SCOPE)
# tokens live on :root on the homepage; here they belong to the wrapper so
# they cannot change main.css's own variables used by the hero
out = re.sub(r':root\s*\{', SCOPE + '{', out)

shared = ['.btn', '.btn--ghost', '.container', '.h2', '.book', '.founder', '.founder__stats']
reset = (
    '/* GENERATED by scripts/build-industry-css.py from homepage.css - do not edit. */\n'
    + ','.join(f'{SCOPE} {c}' for c in shared) + '{ all: revert; box-sizing: border-box; margin: 0; }\n'
    # main.css element rules the homepage never needed to undo
    + f'{SCOPE} section{{ padding: 0; }}\n'
    + f'{SCOPE} .btn:hover,{SCOPE} .btn:active{{ transform: none; }}\n\n'
)
(CSS / 'industry-home.css').write_text(reset + out)
print('wrote', CSS / 'industry-home.css')
