#!/usr/bin/env python3
"""
Generate a paste-ready brief for building the location page inside Elementor's
AI assistant (Angie), or by hand.

Why generated rather than written: the section structure, the copy and the
design tokens all live in build_elementor_location_composition.py. A
hand-written brief would drift from the template the moment either changed.
This walks the same tree, so the brief and the importable JSON always describe
the same page.

Run: python3 scripts/build_angie_brief.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import build_elementor_location_composition as g  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "docs" / "angie-prompt.md"

# What each section is for, in plain language. Angie needs intent, not ids.
SECTION_NOTES = {
    "Hero": ("Hero", "Asymmetric: headline and lede on the left, a bordered "
                     "'survey plate' of market facts on the right. The plate is a "
                     "bordered box with label/value rows separated by hairlines, and a "
                     "small crosshair mark at its top-left corner."),
    "Proof": ("Track record", "A single horizontal band of three large numbers with "
                              "small uppercase labels beneath. No cards, no boxes."),
    "Services": ("Services", "Four large cards in a 2x2 grid. Each card has its own pastel "
                             "palette, a coloured title band at the top, a photo in the "
                             "middle, and a footer with a description and an arrow. The whole "
                             "card is a link."),
    "First30": ("First 30 days", "A dated vertical timeline. Each row is a day marker in "
                                 "small uppercase, then a bold term, then a sentence, "
                                 "separated by hairlines. Deliberately not cards."),
    "Terms": ("Terms", "A stack of clauses. Each is a bold term line followed by a plain "
                       "sentence, separated by hairlines. Reads like a contract, not a "
                       "feature list."),
    "Ask": ("Three questions", "Ruled columns, side by side. Each column is a question in "
                               "bold and an answer below. Deliberately not the card grid "
                               "used by Services."),
    "Area": ("Service area", "Coverage grouped into columns by county. Each column has the "
                             "county name as a heading and its towns listed beneath."),
    "FAQ": ("FAQ", "Question and answer rows separated by hairlines. Question in bold, "
                   "answer in muted body text."),
    "Book": ("Book", "Split layout: copy and a founder byline on one side, the booking "
                     "form embed on the other."),
}


def text_of(node):
    for key in ("title", "paragraph", "text"):
        if key in node.config:
            return node.config[key]["content"]
    return None


def collect_copy(node, out):
    t = text_of(node)
    if t:
        out.append((node.tag, t))
    for c in node.children:
        collect_copy(c, out)


def main():
    tree = g.build_tree()
    lines = []
    add = lines.append

    add("# Build the Apex location page in Elementor")
    add("")
    add("Paste this into Angie (Elementor's AI assistant) one section at a time. Give it the")
    add("**Design system** block first, then one **Section** block per message. Angie loses")
    add("fidelity on long prompts, so do not paste the whole document at once.")
    add("")
    add("> Generated by `scripts/build_angie_brief.py` from the same source tree as")
    add("> `elementor-templates/location-page-native.json`. Regenerate rather than editing.")
    add("")
    add("---")
    add("")
    add("## Before you start: the faster path")
    add("")
    add("`elementor-templates/location-page-native.json` is an importable template that has")
    add("been tested against Elementor 4.2: it imports 226 of 226 elements with all 38 global")
    add("classes and 42 variables. Importing takes about a minute and reproduces the design")
    add("exactly. See `elementor-templates/IMPORT.md`.")
    add("")
    add("Use this brief when you want Angie to build it live, when you want to change the")
    add("design while building, or as the written spec behind the import.")
    add("")
    add("---")
    add("")

    add("## Design system")
    add("")
    add("Set these up first as Elementor **global variables**, then reference them everywhere")
    add("instead of typing hex codes.")
    add("")
    add("**Prefix every global class name with `apex-`.** `container` is a reserved name")
    add("Elementor rejects, and class import merges by label, so an unprefixed `section` or")
    add("`btn` will silently merge with whatever the site already has.")
    add("")
    add("### Colours")
    add("")
    add("| Variable | Value | Use |")
    add("|---|---|---|")
    role = {
        "paper": "page background",
        "paper-raised": "raised surfaces",
        "paper-sunk": "sunk surfaces",
        "ink": "body text and rules",
        "ink-muted": "secondary text",
        "ink-faint": "tertiary text",
        "blue": "primary accent, links, flags",
        "blue-deep": "hover on blue",
        "pink": "secondary accent",
        "pink-hot": "focus rings",
        "mint": "tint",
        "night": "dark surfaces",
        "rule": "hairlines",
        "rule-strong": "stronger hairlines and borders",
    }
    for v in g.GLOBAL_VARIABLES:
        if v["type"] == "color" and v["label"] in role:
            add(f"| `{v['label']}` | `{v['value']}` | {role[v['label']]} |")
    add("")
    add("The four service cards each use a three-colour pastel palette (background, title")
    add("band, rule):")
    add("")
    add("| Card | Background | Band | Rule |")
    add("|---|---|---|---|")
    vals = {v["label"]: v["value"] for v in g.GLOBAL_VARIABLES}
    for letter, name in zip("abcd", ["Google Ads", "Meta Ads", "SEO", "Website"]):
        add(f"| {name} | `{vals['pc-' + letter + '-bg']}` | `{vals['pc-' + letter + '-band']}` "
            f"| `{vals['pc-' + letter + '-rule']}` |")
    add("")
    add("### Spacing")
    add("")
    add("| Variable | Value |")
    add("|---|---|")
    for v in g.GLOBAL_VARIABLES:
        if v["type"] == "size":
            add(f"| `{v['label']}` | `{v['value']}` |")
    add("")
    add("### Type")
    add("")
    add("- One family throughout: **Arimo**, or the site's existing sans. No second family.")
    add("- Three voices only:")
    add("  - **Voice** for headings. Tight tracking, about -0.03em, weight 600.")
    add("  - **Data** for small uppercase labels, wide tracking, about 0.14em. "
        "**Labels and short facts only, never a sentence.** Setting a sentence in tracked "
        "uppercase is the single thing that makes this design look machine-generated.")
    add("  - **Body** in normal case, line-height about 1.45, colour `ink-muted`.")
    add("- Headline sizes are fluid and step up at the laptop breakpoint.")
    add("")
    add("### Layout rules")
    add("")
    add("- Content sits in a centred container, max-width `container-max`, with side padding")
    add("  that steps up at tablet and laptop.")
    add("- Sections are separated by generous vertical padding, roughly 96px rising to 160px")
    add("  on laptop.")
    add("- Hairline rules, 1px in `rule` or `rule-strong`, do most of the separating.")
    add("  **Prefer a rule over a box.** Very little on this page is a card.")
    add("- Corners are mostly square. Only buttons are pill-shaped, and only the service cards")
    add("  have a small radius.")
    add("- **Do not repeat a layout family.** The nine sections use nine different")
    add("  arrangements on purpose. A new section needs a new arrangement, not a second copy")
    add("  of the service card grid.")
    add("")
    add("### Copy rules")
    add("")
    add("- **No em-dashes or en-dashes anywhere.** Use a full stop or a comma.")
    add("- A line either says something only true in this city, or says the sitewide sentence")
    add("  unchanged. Half-localised phrasing like \"built around Austin's highest-value")
    add("  neighborhoods\" is what reads as machine-written.")
    add("- Do not invent local proof: no client names, city-specific statistics, or")
    add("  \"we know this market\" claims.")
    add("")
    add("---")
    add("")

    add("## Sections")
    add("")
    add("Nine, in this order. The copy below is final. Use it verbatim.")
    add("")

    for i, node in enumerate(tree, 1):
        title, note = SECTION_NOTES.get(node.cid, (node.cid, ""))
        add(f"### {i}. {title}")
        add("")
        add(note)
        add("")
        copy = []
        collect_copy(node, copy)
        if copy:
            add("Copy:")
            add("")
            add("```")
            for tag, text in copy:
                kind = {"e-heading": "H", "e-paragraph": "P", "e-button": "BUTTON"}.get(tag, tag)
                add(f"[{kind}] {text}")
            add("```")
            add("")

    add("---")
    add("")
    add("## Three things Angie cannot do, that need a manual step")
    add("")
    add("1. **The booking form.** Leave an empty container in the Book section, then add an")
    add("   Elementor **HTML widget** with this iframe:")
    add("")
    add("   ```html")
    add(f'   <iframe src="{g.GHL_FORM}"')
    add('           title="Book a free strategy call with Apex Marketing"')
    add('           style="width:100%;min-height:640px;border:0;display:block" loading="lazy"></iframe>')
    add("   ```")
    add("")
    add("2. **A collapsing FAQ.** The atomic element set has no accordion. Either leave the six")
    add("   rows open, or use Elementor Pro's **Accordion** widget. Same copy either way.")
    add("")
    add("3. **The faint grid texture** behind each section, about 5% opacity. It is a repeating")
    add("   grid, and Elementor's gradient overlay has no background-size, so it cannot be made")
    add("   from a gradient. To add it: upload a 220x220 PNG of one grid cell, a 1px ink line on")
    add("   the top and left edges and transparent elsewhere, then set it as a background image")
    add("   overlay with repeat, sized 220x220. Purely decorative.")
    add("")
    add("## When it is built")
    add("")
    add("The city-specific strings become dynamic tags against the `apex_location` post type,")
    add("so one template serves every city. The fields are `apex_city`, `apex_state`,")
    add("`apex_state_abbr`, `apex_timezone`, `apex_hero_h1` and `apex_hero_lede`, plus the")
    add("`apex_service_area` taxonomy for coverage. See `docs/elementor-authoring.md` section 7.")
    add("")
    add("One number changes when you do. The hero plate's \"Areas served\" reads **8** here,")
    add("meaning the nearby towns, while `apex_location_areas_count()` returns **9**, meaning")
    add("every town in the coverage taxonomy including the city itself. Both are right for")
    add("their own definition, so decide which one the plate should show before binding it,")
    add("rather than being surprised when the number moves.")
    add("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"

    for ch, name in (("—", "em-dash"), ("–", "en-dash")):
        if ch in text:
            raise SystemExit(f"{name} found in the brief; rewrite the sentence.")

    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO_ROOT)}: {len(tree)} sections, "
          f"~{len(text.split())} words. No dashes.")


if __name__ == "__main__":
    main()
